### PR TITLE
Fix missing newline in debug_message

### PR DESCRIPTION
**Pull request by gesslar**

### CODE REVIEW

**Comment by thefallentree** [comment]
lets just remove this line.. a lot people find it really confusing.. or we need to ignore common values like 64

**Comment by gesslar** [comment]
I don't even know why I'm getting that message. Because I am getting it on
a mapping. And mapping is handled.

Idk what type 64 is.

 I don't think it should be using debug message though. But, they should
all terminate with `\n`.

I'm going to do a sweep sometime soon to ensure they are. Because this is
the second one I've found

**Comment by gesslar** [comment]
Okay, it also does it for buffers, which is type 256

`save_svalue: unknown type 256 ignored.`

**Comment by thefallentree** [comment]
yeah, let's just get rid of those. although we should probably save/restore buffers ..

**Pull request merged**
