### PR TITLE
Documemtations, part 2

### PR DESCRIPTION
**Pull request by Shea690901**
A complete set of man pages for the current packages/db and an addition for save_object…

### CODE REVIEW

**Comment by thefallentree** [comment]
I'm not sure we should continue to write in man page format, in fact I'm all for converting to markdown instead.  I have a script in fluffos/fluffos.github.io to convert them into MD. 

let's do that after.

**Comment by Shea690901** [comment]
Uff…
Couldn't you have said this before?
I had to look for some documemtation on *roff macros to know how to include url's…

I'm all for converting to md…
next thing would be either a md parser in lpc or direct build into the driver :)

**Comment by quixadhal** [comment]
I like nroff.  I hate markdown.

nroff is nice because it can easily adjust to any terminal size, and as an
added bonus, you can add the LPC documentation directory (nroff sources) to
your MANPATH and be able to access them from the actual unix man command.

If you're going to destroy the useful nroff versions, please let me know
the commit you do this in, so I can branch and preserve them in my own copy.

**Comment by thefallentree** [comment]
@quixadhal You will always have that in the history, plus, I suggest creating a MD -> nroff converter, so you will be able to convert it whenever you like.

We are just changing main document format to MD here, it is easier to write (although less official looking) and easier to render in a lot of places.

**Comment by Shea690901** [comment]
Imho md is easier to maintain than \*roff and using the current sections isn't a good idea anyway:
(e.g., man printf)
If you want to use standard *man* a numbering like
- applies: LPC2
- efuns: LPC3
would he better…

On the subject of output formats:
- plain text  
   as long one hasn't got anything better for in game
- (x)html  
   for the online documentation
- texi  
   some like texinfo better than \*roff and the info browser even understands links ;)
- (La)TeX  
  a printed version? Could also be converted into pdf…

And before someone complains about the converters:
I've already found one, apparently [pandoc](http://pandoc.org/) does all of that and more…
Sadly it's written in haskall

**Comment by quixadhal** [comment]
Is there a markdown -> nroff converter that can be bundles as a utility
program?  I can't be the ONLY person who likes having LPC man pages
available from the system command line.  Well... maybe I can be, as people
die off. *chuckle*

Not sure something in haskall is useful for anyone but those of us reading
this right now.  The odds of having haskell installed in 10 years might be
pretty small. :)

**Comment by Shea690901** [comment]
Apparently pandoc can also convert to groff…
As fas as I can tell, the only thing speaking against it would be the source language of pandoc itself…
At least it's in the repository of many linux distros:
- debian/uubuntu (64-bit)
- slackware
- arch
- fedora
- nixos
- opensuse
- gentoo

Also available for:
- windoze
- macosx
- netbsd/freebsd

And of course as source (blergh, haskell…)

**Comment by quixadhal** [comment]
Not sure if groff is compatible with the man command.  As far as I know, on
linux these days, man basically does "nroff -man", which itself invokes
groff with additional options, and that in turn invokes troff to actually
do the work.

I guess the empirical test would be... make your fancy new markdown pages,
have this thing convert them to "groff" source with filenames ending in .6,
go make a man directory in your home directory and put them in
$HOME/man/man6/ and add that to your MANPATH variable in your shell.  If
you type "man call_out" and it looks like a man page and not a poorly
formatted web page, then I guess it works. :)

Be sure to add that dependency in the installation documentation, as a "if
you want man pages, use this" note.

**Comment by Shea690901** [comment]
Sadly something someone other has to do for the foreseeable future :(
I'm happy I've got a vim and git running on my tablet (actualy two git, one to work with, ankther just for pushing) and I don't know how long until I get a real computer again :(

**Pull request merged**
