### PR TITLE
<core>(autotools): overhaul

### PR DESCRIPTION
**Pull request by Shea690901**
Convenience patch:
- added entries for vim generated files to .gitignore
- added driver.exe{,.old} to src/.gitignore
- added'PROG_DUMP to src/testsuite/.gitignore

Overhaul:
- upgrade to autoconf 2.69
- added #ifdef/#endif wrapper to configure.h as protection against
  multiple includes (autoheader)
- added a little eye candy
- added section for AC_ARG_ENABLE and AC_ARG_WITH
- added some comments concerning the relevance behind the entrys
- added some missing (conditional) tests
- added some new entrys
- added still more eye candy
- allow for name transformations of installed programs
- build.FluffOS now may be called from any directory, as before all by
  configure generated files will reside in the current working directory
  (build directory)
- configure now generates a version string according either tarball
  version or git version (taged) and the diversion of the current
  branch. (still needs Makefile support)
- configure now optionaly stores it's cmdline (not yet used)
- configure.ac now supports a build directory different to the source
  directory
- removed PACKAGE_CORE and PACKAGE_OPS as chooseable packages
  (forced incorporation via CFLAGS/CXXFLAGS)
- removed doubled tests
- removed some no longer neccessary tests from configure.ac
- removing error message concerning <no target clean> when building with
  jemalloc disabled.
- removing error messages concerning missing paramter to rm while
  running "make clean" when there are no backup files by either vim or
  patch or files containing rejected diff hunks.
- renamed 'gcov.m4' => 'fluffos_check_gcov.m4'
- reordered some tests
- reworked <check for programs> section
    - added protection against compiler option "-flto" under cygwin (currently dysfunct)
    - added some AC_PROG_xxx checks
    - added subsection for plain C compiler
- several files included at least one of 'sys/time.h' or 'time.h'
  without using the autoconf result of what should be included...
- sorted old entrys
- using 'build-aux' for all files needed by autotools cleans the main
  directory...

TODO:
- Makefile support for build directory

### CODE REVIEW

**Comment by Shea690901** [comment]
Phew...
One hell of a patch....
Tested on cygwin and at least partly on travis....
Haven't looked into the travis builds for quite some time, what's this with the first four runs fail???
Ok, 2 & 4 apparently are due to some error with jemalloc (perhaps upgrade to current version [5.0.1] ?)

**Comment by thefallentree** [comment]
I'm in principle okay with this change,  however, have you tested it on linux? It is really important platform we need to support.

**Comment by thefallentree** [comment]
This is very good,  now that libtool is working , we should just dynamically load packages instead.  No more local_options for packages. just build it all.

**Comment by quixadhal** [comment]
What systems use /opt nowadays?  Last time I saw that was Solaris, about 20 years ago.  Certainly not a good “default” to use.  For the average Linux person, I’d probably make it default to $HOME or nothing at all.

Also, `dirname $(pwd)` is just an overly elaborate way to say “..”

$PWD always evaluates to your current directory, and dirname always strips the trailing element given to it (assuming it is a filename with a path attached).

Sent from Mail for Windows 10

**Pull request merged**
