### PR TITLE
Changes for 20170907 release.

### PR DESCRIPTION
**Pull request by thefallentree**

### CODE REVIEW

**Comment by keeperofkeysAU** [comment]
Removing DWLIB for discworld mudlib support is insult, I would really hope you plan on re-adding it

**Comment by thefallentree** [comment]
@keeperofkeysAU please don't be so easily offended. No one is intended to insult anyone here. 

DWLIB support is broken for almost 2 years now, and no one seems to care enough to fix it, that's the reason it is gone. The 3.0 driver codebase needs to be maintained, because it is actually still being used. (more than a lot of people would think here, apparently).

The open source rule is that if you care enough about it , just send a PR, if it passes the tests I am happy to include it.

**Comment by Shea690901** [comment]
REVIEW (d6fb6db)

Why didn´t you wrote (`src/packages/core/replace_program.cc`):
``` C
if (name_len < 3 || name[name_len - 2] != '.' || name[name_len - 1] != 'c') {
     strcat(name, ".c");
   }
```
instead of

``` C
if (name_len < 3) {
    strcat(name, ".c");
} else {
   if (name[name_len - 2] != '.' || name[name_len - 1] != 'c') {
     strcat(name, ".c");
   }
}
``` ?

That way the code should be a little bit more compact even without optimization...

**Comment by quixadhal** [comment]
This changes the functionality of the original.  The old code appended “.c” to any filename which didn’t already end in “.c”.  This new one won’t affect filenames like “a” or “xy”.  Is that intended?

Sent from Mail for Windows 10

**Comment by thefallentree** [comment]
if namelen<3 , it is impossible to end with .c。

the code here sure is bad, and should be rewrite with std:string.

Now, do you guys want to send a PR?

**Comment by quixadhal** [comment]
What if you pass in “.c” as the filename?  You’d get “.c.c” out with the length check, right?
Not that “.c” by itself is a very good filename choice, but…   Changing it from < 3 to < 2 would
close that, although you’d still end up with “.” Becoming “..c”… but that’s what the old version
would have done as well (well, technically the old one would have crashed trying to do the
dereference to position -1).

Sent from Mail for Windows 10

**Comment by cartercheng** [comment]
I think that perhaps not such a good idea to take out these two packages over fixing them. I suspect the debug stuff is used by quite a few people. As for dwlib, I actually hate to see this go too.

**Comment by thefallentree** [comment]
Dwlib is later restored. As for debug.c it was just called debug.c

**Pull request merged**
