### PR TITLE
Migrate networking code to Golang

### PR DESCRIPTION
**Pull request by thefallentree**
1. Main loop driven by golang.
2. Multi-threaded networking code (wrapping libtelnet)
3. Foundation for Go-based efun.

### CODE REVIEW

**Comment by thefallentree** [comment]
the CI correctly passes now. 

The remaining bits (for my self) : 

1. Solve multi threading issue for libtelnet  (should remove  ip->telnet handle) 
2. Implement telnet_send_text_async() 
3. More testing on connection disconnection error handling.

**Comment by Shea690901** [comment]
Er...

> Foundation for Go-based efun.

Are you planing to change everything to go? Or just as option for module coders?

**Comment by thefallentree** [comment]
some efun can be rewrote in go,  but it is certainly optional and in no
rush to change everything.

**Comment by cartercheng** [comment]
I haven't yet looked at go's foreign function interface to c. Is interfacing with the global stack easy to do?

**Comment by Shea690901** [comment]
And don´t forget the C++ interface ;)

**Comment by cartercheng** [comment]
I doubt you can interface with c++ since the language support for objects isn't there. It's one of the reservations I have about golang. It seems not to handle objects and typing very well (or at least one or the other). For example ML I think has a very nice typing system and I guess quite a few languages now do OO quite okay. I think few do typing to the extent ML does for OO since there are some theoretical problems.

**Comment by thefallentree** [comment]
They all support C interface, whatever OO you need is just a simple wrapper
function away.

**Comment by cartercheng** [comment]
Actually I think I might embark on a separate project that is related to fluffos. I want to rewrite the vm possibly in another language. My first thought is java since it supports dynamic loading. The idea would be to write a light weight runtime to replace the vm and write a lpc->java translator that converts lpc (after syntax and semantic checking) into java which is compiled by calling javac. It would have been nice if this could be done in golang as well but unfortunately since golang doesn't support dynamic loading in the current implementation this is a bit difficult. The main difficulty with java is implementing type mixed efficiently but perhaps it doesn't matter too much since one can use some tricks not available in the current vm to convert a lot of things to primitive types which could be quite fast.

**Comment by thefallentree** [comment]
That sounds cool, and it has been tried before, its good to have someone
try again.

But like you said it is a separate route and you may need a separate repo
to host the code and issues.

**Comment by cartercheng** [comment]
I was actually wondering if it might be possible to interface the code with modified version of the go code you are working on. I will see if I have time to study this problem further. It is quite time consuming which is why I think previous tempts have failed. Most people just give up because it takes a very long time to even clone an existing compiler in another language with slightly different tools. And then there is the runtime system and all the efuns etc.

**Comment by cartercheng** [comment]
I am actually surprised by how messy grammar.pre.y is i thought that fluffos/mudos had moved to parse trees but there is a lot of code in grammar.pre.y for various checks which in a canonical compiler should not be done at this point but on the AST. The file because of these "checks" is huge :(.

**Comment by thefallentree** [comment]
this need more work, abandoned for now.

**Pull request closed without merging**
