### PR TITLE
fixes alpine static linking

### PR DESCRIPTION
**Pull request by lostsnow**

### CODE REVIEW

**Comment by thefallentree** [comment]
why was ci-sanitizer broken?

**Comment by lostsnow** [comment]
> 
> 
> why was ci-sanitizer broken?

It looks like the previous commit is now showing the same error(in my fork): 
https://github.com/lostsnow/fluffos/runs/2656902235

**Comment by lostsnow** [comment]
https://github.com/fluffos/fluffos/blob/dd180d09729547cddff721b32a36b55a4f2fce3e/.github/workflows/ci.yml#L34'

The new version of the [github action image](https://github.com/actions/virtual-environments/blob/ubuntu20/20210517.1/images/linux/Ubuntu2004-README.md) automatically removes `clang-6.0`:

图片

**Comment by lostsnow** [comment]
gcc-11 break the clang build 
https://github.com/actions/virtual-environments/issues/3376

**Pull request merged**
