### PR TITLE
<feat>(strutils): extension & documentation

### PR DESCRIPTION
**Pull request by Shea690901**
- added possibility to trim other characters than whitespace
- extended to properly support move operation for string to be trimmed
- added version taking a const std::string reference
- added documentation

Signed-off-by: Shea690901 <ginny690901@hotmail.de>

### CODE REVIEW

**Comment by thefallentree** [comment]
std::isspace covers more characters actually: see https://en.cppreference.com/w/cpp/string/byte/isspace

**Comment by thefallentree** [comment]
we can make second argument to be default empty string, in which case we still use std::isspace internally.

**Comment by quixadhal** [comment]
Just as a caution, it looks like std::isspace is not UTF-8 aware and expects the underlying string to be made up of unsigned chars.There IS a version that’s locale aware, as well as a “wide char” version, as mentioned in the man page you linked.I only mention it because I saw you were working on some UTF-8 stuff earlier. Sent from Mail for Windows 10 From: Yucong SunSent: Wednesday, November 27, 2019 2:05 PMTo: fluffos/fluffosCc: SubscribedSubject: Re: [fluffos/fluffos] <feat>(strutils): extension & documentation (#530) we can make second argument to be default empty string, in which case we still use std::isspace internally.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by thefallentree** [comment]
In this specific case of use std::isspace , I think we are fine, because string internal representation will be utf-8, and std::isspace will work fine over there. 

You can read https://utf8everywhere.org , and that's the general guideline I'm using to make fluffos codebase work under utf8 for both linux and windows

**Comment by quixadhal** [comment]
The thing it won’t catch is UTF-8 whitespace characters that are multi-byte encodings.  I don’t know how many such things there are, there are a lot of punctuation symbols such as 『 and 』for example.  I think the non-breaking space might qualify.  It probably won’t show up very often, punctuation is much more of an issue, if you’re using ispunct() anywhere. Sent from Mail for Windows 10 From: Yucong SunSent: Wednesday, November 27, 2019 2:45 PMTo: fluffos/fluffosCc: Dread Quixadhal; CommentSubject: Re: [fluffos/fluffos] <feat>(strutils): extension & documentation (#530) In this specific case of use std::isspace , I think we are fine, because string internal representation will be utf-8, and std::isspace will work fine over there.You can read https://utf8everywhere.org , and that's the general guideline I'm using to make fluffos codebase work under utf8 for both linux and windows—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Shea690901** [comment]
Sorry, didn't notice the resulting problems with package/trim....

**Comment by Shea690901** [comment]
According https://en.cppreference.com/w/cpp/string/byte/isspace my version checks for the same ASCII values, only with one function call less...

**Comment by thefallentree** [comment]
It looks like there are bugs in the current patch

```
==7496==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffe9d757538 at pc 0x56252e33bbee bp 0x7ffe9d7573f0 sp 0x7ffe9d7573e0
READ of size 8 at 0x7ffe9d757538 thread T0
    #0 0x56252e33bbed in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::length() const /usr/include/c++/7/bits/basic_string.h:927
    #1 0x56252e34b30d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/runner/work/fluffos/fluffos/build/bin/driver+0x59030d)
    #2 0x56252e345447 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/7/bits/basic_string.h:1356
    #3 0x56252e33ee36 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/7/bits/basic_string.h:685
    #4 0x56252e6b0e9e in _trim_impl /home/runner/work/fluffos/fluffos/src/packages/trim/trim.cc:67
    #5 0x56252e6b100a in f_trim() /home/runner/work/fluffos/fluffos/src/packages/trim/trim.cc:78

```

**Comment by Shea690901** [comment]
????
I've just done a clean rebuild of this patch
```
cd build
rm -rf *
cmake ..
make
```
and run the tests with this newly build driver:
no error (well except for the expected one from crasher ;) )...

**Comment by thefallentree** [comment]
That’s because you didn’t run it under sanitizer, and it won’t complain
about memory corruption.

**Comment by Shea690901** [comment]
*grmbl*

OK. Tested under sanitizer and got the same problem.
Looking at the fix for that problem I think that was either a false positive or a bug within the optimizer (personal I think it's the former, but I haven't tried to build without optimizer)...

Apparently I had hit the undo button shortly before saving the trim package and tried to trim the allready trimmed string. That should either have been optimized away or shouldn't have generated a stack access error.
Regardless of the reason: 
Last compile (under sanitizer) yield no errors...

**Comment by thefallentree** [comment]
good, it seems whatever you did fixed the issue :-)

**Pull request merged**
